### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by amandel** [jfrog/jenkins-jfrog-plugin#23]
### Describe the bug

Information in `README.md`  not sufficient for setup.

### Current behavior

Setting up the integration based on the `README.md` section _Automatic installation from Artifactory_.

Step 1 proposes to set up a jfrog-cli-remote repository. But it does not explain the settings to use for the repo. At least the repository type should be documented to avoid guessing.

In step 3 there is a typo `jfrog-cli-remote` is now called `jfrog-cle-remote`. 

### JFrog plugin version

head 8ba9e663b155d3067d9b81597a8041a30f4b8c66

### JFrog CLI version

not relevant

### Operating system type and version

not relevant

**Comment by yahavi** [comment]
@amandel thanks for reporting this issue!
The required type of the remote repository is "Generic". 
We'll add it to the README and we will fix the typo.

**Comment by amandel** [comment]
Thanks for looking into this. Using Generic feels obvious but it did not work for me in the 1st place because of a different issue. So it was not clear to me what could be the cause.
