### ISSUE TITLE
No default value for JFROG_BINARY_PATH

### ISSUE THREAD

**Issue by alexymantha** [jfrog/jenkins-jfrog-plugin#33]
### Describe the bug

When JFROG_BINARY_PATH is not specified and the tool is not used explicitly, the `jf` step tries to run `null/jf` which does not work. It would be nice if the step tried to run `jf` and run the JFrog CLI that is on the path.

### Current behavior

If JFROG_BINARY_PATH is not specified, it is null and tries to run `null/jf`

### Reproduction steps

1. Do not use the globally defined tool
2. Do not specify JFROG_BINARY_PATH
3. Try to use the jf step

It will fail with described problem.

### Expected behavior

It should default to use the `jf` that is on the path

### JFrog plugin version

1.0.5

### JFrog CLI version

2.34.2

### Operating system type and version

Many different versions of linux, mainly debian and alpine

### JFrog Artifactory version

N/A

### JFrog Xray version

N/A

**Comment by yahavi** [comment]
Thanks for using the Jenkins JFrog plugin @alexymantha!
We'll look into it soon.

**Comment by yahavi** [comment]
@alexymantha,
Jenkins JFrog plugin 1.1.0 is released. This version includes support for using `jf` from the system path, if not provided.
Feel free to upgrade - we'd appreciate your feedback on that!
