### ISSUE TITLE
Doesn't work on Windows nodes

### ISSUE THREAD

**Issue by larsskj** [jfrog/jenkins-jfrog-plugin#34]
### Describe the bug

We're experimenting with the new JFrog plugin in order to implement it in our setup.

However, today we learned that it doesn't work on Windows nodes: When a pipeline tries to call `jf.exe` it fails as it tries to execute

```
cmd.exe /C "null\jf.exe c add ...
```

We alse found that the environment variable `JFROG_BINARY_PATH` has the value `null`.

### Current behavior

See above.

### Reproduction steps

Setup the plugin as recommended with the JFrog CLI installed as a global tool - and try running any command involving `jf` on a Windows node.

### Expected behavior

That it works like it does on Linux.

### JFrog plugin version

1.0.5

### JFrog CLI version

latest as of March 3rd 2023.

### Operating system type and version

Jenkins stock Docker image - 2.393 on the master / Windows 10 on node

**Comment by getrostt** [comment]
The tool directory on the node does not contain the tool either.

**Comment by getrostt** [comment]
The reason was a missing auto installation of the tool due to CasC (the generated yaml omits the tool installation configuration).

See here https://github.com/jenkinsci/jfrog-plugin/issues/7

**Comment by larsskj** [comment]
Yes - sorry - this was a mistake on our side.

Let's close this ticket.
