### ISSUE TITLE
Jenkins complains about serialization of an anonymous inner class

### ISSUE THREAD

**Issue by enaess** [jfrog/jenkins-jfrog-plugin#76]
### Describe the bug

When using the toolkit { jfrog "jfrog-cli" } on stage that are executed on a different host acting as a jenkins-agent (a Linux host using remoting.jar via SSH), we are seeing the following warning in the for that node on Jenkins (2.401.3).

```Aug 03, 2023 4:56:01 PM org.jenkinsci.remoting.util.AnonymousClassWarnings warn
WARNING: Attempt to (de-)serialize anonymous class io.jenkins.plugins.jfrog.BinaryInstaller$1; see: https://jenkins.io/redirect/serialization-of-anonymous-classes/
```

### Current behavior

Logs a warning about use of an anonymous inner class. Not sure what that actually means and if it breaks anything.  But one should have a look and figure of if this will cause a problem. Shouldn't be too hard refactoring the code such that it will function properly.

### Reproduction steps

Setup Jenkins, create a new pipeline that executes the stage on a different host.

### Expected behavior

Should not see this message.

### JFrog plugin version

1.4.0

### JFrog CLI version

2.44.0

### Operating system type and version

Linux

### JFrog Artifactory version

-

### JFrog Xray version

-

**Comment by yahavi** [comment]
@enaess 
Thanks for reporting this issue.
We fixed it by https://github.com/jfrog/jenkins-jfrog-plugin/pull/81 in the latest release - [1.5.0](https://github.com/jfrog/jenkins-jfrog-plugin/releases/tag/jfrog-1.5.0).
Feel free to upgrade - we'd appreciate your feedback on that.
