### ISSUE TITLE
Binary being downloaded for every call of the plugin

### ISSUE THREAD

**Issue by ca-monteiro** [jfrog/jenkins-jfrog-plugin#77]
### Describe the bug

After placing Artifactory behind a HTTP2 Load balancer, the HTTP headers coming from Artifactory responses started to be re-written to lower case, in conformity with the [RFC](https://www.rfc-editor.org/rfc/rfc9113#name-http-fields). 

This is causing the Jfrog CLI plugin to never read the **x-checksum-sha256** header because is trying to do a case sensitive [compare](https://github.com/jfrog/jenkins-jfrog-plugin/blob/cb3a59ac0dc60d9c89d68b85191992b879d1c050/src/main/java/io/jenkins/plugins/jfrog/BinaryInstaller.java#L155). This causes the plugin to download the jf binary everytime a plugin step is called.

### Current behavior

Multiple downloads of the jf binary during the same pipeline running on the same Jenkins agent.

`[Pipeline] { (Show JFrog configs)
[Pipeline] tool
Download 'jf' latest version from: https://*****/artifactory/jfrog-cli/v2-jf/[RELEASE]/jfrog-cli-linux-amd64/jf
[Pipeline] envVarsForTool
Download 'jf' latest version from: https://*****/artifactory/jfrog-cli/v2-jf/[RELEASE]/jfrog-cli-linux-amd64/jf
[Pipeline] withEnv
[Pipeline] { (Run Xray Scan on Artifacts)
Download 'jf' latest version from: https://*****/artifactory/jfrog-cli/v2-jf/[RELEASE]/jfrog-cli-linux-amd64/jf`

### Expected behavior

Following the HTTP [RFC](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2) the plugin should match HTTP headers in a case insensitive mode.

### JFrog plugin version

1.4.0

### JFrog CLI version

2.45.0

### Operating system type and version

jenkins/jenkins:2.409-alpine

### JFrog Artifactory version

Enterprise Plus 7.35.2

**Comment by yahavi** [comment]
@ca-monteiro,
Jenkins JFrog plugin [1.5.0](https://github.com/jfrog/jenkins-jfrog-plugin/releases/tag/jfrog-1.5.0) has been released. This version includes your fix.
Please let us know if that works for you.
