### ISSUE TITLE
no_proxy fails with urls containing a dash

### ISSUE THREAD

**Issue by wum5r** [jfrog/jenkins-jfrog-plugin#93]
### Describe the bug

I have setup the jenkins-jfrog-plugin to download the cli tool from a local Artifactory. We have a  Artifactory server in a company network with the url 01-artifactory.test.com. We have setup a proxy with the Artifactory url in the no proxy list. But the download from Artifactory fails with a 403 from the proxy. It looks like the hostname for our Artifactory is cut at the dash so it is searched for 01 in the no_proxy list instead of 01-artifactory.test.com

### Current behavior

org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: b2c56d0d-6eec-4164-9ad2-473f4b9fc29e
java.io.IOException: JFrog service failed. Received 403

### Reproduction steps

Add an artifactory server with an URL containig a '-' in a setup with a proxy and add the server url to the no_proxy list

### Expected behavior

Download from artifactory is done in the internal network without using the proxy

### JFrog plugin version

1.5.0

### JFrog CLI version

2.57.0

### Operating system type and version

Windows 10 22H2

### JFrog Artifactory version

7.68.1.4

**Comment by harryg-bosch** [comment]
Probably exactly same here. For also install from Artifactory fails because it goes through the proxy although I used proper no proxy settings.
My internal Artifactory also has a dash in its name, so this could really be the reason.
Workaround is difficult as public jFrog repo is not allowed through our proxy. So I'm now using an ugly wget workaround...

@yahavi or anyone from the jFrog team, can you please check this? It is quite annoying.

**Comment by yahavi** [comment]
@wum5r @harryg-bosch

The Jenkins JFrog plugin version [1.5.1](https://github.com/jfrog/jenkins-jfrog-plugin/releases) has been released. This version includes the [fix](https://github.com/jfrog/jenkins-jfrog-plugin/pull/97) for the issue.

Please feel free to upgrade, and we would appreciate your feedback on this.

**Comment by harryg-bosch** [comment]
Great, thanks a lot, that was fast!

**Comment by wum5r** [comment]
I have installed the new version of the plugin and now everything works as expected.
Thanks a lot for the quick support
